version: '3.4'

x-common-variables: &common-variables
  PORT: '3000'
  DB_HOST: 'mysql'
  DB_NAME: 'octopus'
  DB_PORT: '3306'
  DB_USER: 'root'
  DB_PASS: 'root'
  REDIS_HOST: 'redis://redis:6379'
  SALT: 'salty'
  PRIVATE_KEY: |-
      -----BEGIN RSA PRIVATE KEY-----
      MIICXgIBAAKBgQDeUQU6jLD8Ez+om48UWaBpLFuJR24iD4m/BhVALmGeQkp+eRCk
      25dQsrJSDJ7hjerrdj0ZfxGuDgnmVmOcqtIvQR79GxSYn4OYcP7gMCSk9R13OAx3
      CwfpAaHISd6/DsIxAiJ8INOA3qqWsEfKp6RnTmTXQi35IRdTrrsHrAiziwIDAQAB
      AoGADUb1cvu4DjXwFVfFAcgghmd5yAcWEr6u0VPBrSWX+uWmoUsFrXLX5J/nenL6
      gioBn7JeD8nA+o4oFTOPm2mwR7mma6lrx/cm+Ulz2JrMvoU1F+juTtAoTiYFmi19
      i7Xxdvrxis3IEOhpNSeqN7Q894rSsuiQD58WpMR4hTWyjlECQQDg7bEeeLlSGmF1
      jVqw/YVDS2hwtP5Y6Cr1h1vqc7UX4IrrcJxce1Qx/8X+/S/6H0B4CwK0KH9o/Nbx
      erAmHKdNAkEA/Qb1ZjYCbg18i+rH6DziFclZ3QrVBNrqPZEOo7hmvmykXIO2vHBU
      aQeW8nohYoVMAHTtEKO/Gvr4i7hRXFbKNwJBAMYrJH2AR2Y6r9rtqxV8h0h+y4lh
      LSYPhqnDlAu/3bEnt70u/dPNJKTYgAzj7L0lg5s/uCYZ+Ab7nDQsr70kSZECQQC0
      d30Z7JWpFtdpGAiC/MGoFleQz4QFlXoSdV6CqSgm02gbUBpKpredvbsMsM0U7su5
      W6wl/RR10uDpDoqBGKnbAkEAzNNQTrPv6cnSMko9ccjyyq70i5myxMyuJdLsLKMH
      xNO09nMsdTVxfGJBgvAN8zSFsHOPyLqFWJVJlAOZCpz/aw==
      -----END RSA PRIVATE KEY-----

services:
  redis:
    image: 'redis:alpine'
  mysql:
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
  web:
    environment: *common-variables
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on:
      - redis
      - mysql
  celery:
    environment: *common-variables
    build:
      context: .
      dockerfile: celery.Dockerfile
    depends_on:
      - redis
      - mysql