version: '3.4'

x-common-variables: &common-variables
  PORT: '80'
  DB_HOST: 'mysql'
  DB_NAME: 'octopus'
  DB_PORT: '3306'
  DB_USER: 'root'
  DB_PASS: 'root'
  REDIS_HOST: 'redis://redis:6379'
  SALT_FILE: '/run/secrets/salt'
  PRIVATE_KEY_FILE: '/run/secrets/private_key'

secrets:
  salt:
    file: ./salt.txt
  private_key:
    file: ./private.key

services:
  redis:
    image: 'redis:alpine'
  mysql:
    image: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: octopus
  web:
    environment: *common-variables
    secrets:
      - salt
      - private_key
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on:
      - redis
      - mysql
  celery:
    environment: *common-variables
    secrets:
      - salt
      - private_key
    build:
      context: .
      dockerfile: celery.Dockerfile
    depends_on:
      - redis
      - mysql